name: wizarr-release

on:
    release:
        types: [ published ]
    workflow_dispatch: { }

env:
    PYTHON_VERSION: '3.12'
    NODE_VERSION: '20'

jobs:
    # ──────────────────── Docker Release Image ────────────────────
    release:
        runs-on: ubuntu-latest
        permissions:
            contents: read
            packages: write
        
        steps:
            -   uses: actions/checkout@v4

            -   name: Log in to GHCR
                uses: docker/login-action@v3
                with:
                    registry: ghcr.io
                    username: ${{ github.actor }}
                    password: ${{ secrets.GITHUB_TOKEN }}

            -   name: Set up QEMU
                uses: docker/setup-qemu-action@v3

            -   name: Set up Buildx
                uses: docker/setup-buildx-action@v3
                with:
                    install: true

            -   name: Build & push multi-arch release image
                uses: docker/build-push-action@v5
                with:
                    context: .
                    push: true
                    platforms: linux/amd64,linux/arm64
                    tags: |
                        ghcr.io/${{ github.repository_owner }}/wizarr:latest
                        ghcr.io/${{ github.repository_owner }}/wizarr:${{ github.event.release.tag_name }}
                    build-args: |
                        APP_VERSION=${{ github.event.release.tag_name }}
                    cache-from: type=gha
                    cache-to: type=gha,mode=max